[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/douban"
  to = "/.netlify/functions/douban"
  status = 200

[[redirects]]
  from = "/api/douban/*"
  to = "/.netlify/functions/douban"
  status = 200